<?php

include_once('eduglu_group_reader.features.inc');

/**
 * Implementation of hook_nodeapi
 
function eduglu_group_reader_nodeapi ($node, $op, $a3 = NULL,
$a4 = NULL) {
	dpm($op);
	dpm($node->type);
  if ($op == 'insert' && $node->type == "feed_item") { // Check if new node is being inserted + if correct node type.
    $owner_feed_nid = $node->feeds_node_item->feed_nid;
	dpm($owner_feed_nid . " <- Owner Feed");
	dpm($node);
	// Grab the parent feed nid then the group id for the the parent feed node.
    if (!$owner_feed_nid) {
      return;
    }
    $results = db_query("SELECT group_nid
                              FROM {og_ancestry}
                              WHERE nid = %d", $owner_feed_nid);
	dpm(node_load(array('nid' => $owner_feed_nid)));
	while($data = db_fetch_array($results)) {
    	$group_association = array(
    	  'nid' => $node->nid,
    	  'group_nid' => $data['group_nid']
    	  );
		dpm($data);
		dpm($group_association);
    	drupal_write_record('og_ancestry', $group_association); // Use drupal_write_record() to add the the new feed item to the og_ancestry table.
	}
  }
}
*/
